export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_CATEGORIES = "CREATE_CATEGORIES";
